# Generated by Django 3.0.8 on 2020-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200809_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image_alt',
            field=models.CharField(default='Alt text goes here', max_length=500),
            preserve_default=False,
        ),
    ]
