# Generated by Django 3.0.8 on 2020-08-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_header_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image_alt',
            new_name='header_image_subtitle',
        ),
    ]
